import { z } from 'zod';
import type { ActionExecutor, ActionContext, ActionResult } from '../types.js';
import { createPullRequest } from '../../github/githubPullRequestService.js';
import { enrichPRDescription } from '../../ai/index.js';

const CreatePRConfigSchema = z.object({
  sourceActionId: z.string().optional(),
}).passthrough();

export const createPRExecutor: ActionExecutor = {
  type: 'create_pr',

  async execute(ctx: ActionContext): Promise<ActionResult> {
    const { task, project, apiKey, knowledgeContext } = ctx;
    const config = CreatePRConfigSchema.parse(JSON.parse(ctx.action.config || '{}'));

    if (!ctx.repo) {
      throw new Error('Cannot create PR: project has no GitHub repository connected');
    }
    if (!ctx.plan.branchName) {
      throw new Error('Cannot create PR: no feature branch exists on this plan');
    }

    // Get code summary from a previous generate_code result if available
    let codeSummary: string | undefined;
    if (config.sourceActionId) {
      const sourceResult = ctx.previousResults.get(config.sourceActionId) as
        | { data?: { summary?: string } }
        | undefined;
      codeSummary = sourceResult?.data?.summary;
    }

    // Fetch parent task title and acceptance criteria for richer PR context
    const taskWithContext = await ctx.prisma.task.findUnique({
      where: { taskId: task.taskId },
      select: {
        acceptanceCriteria: true,
        parentTask: { select: { title: true } },
      },
    });

    // Build PR body (AI-enriched if possible, fallback to basic)
    let prBody: string;
    try {
      prBody = await enrichPRDescription(
        apiKey,
        task.title,
        task.description ?? '',
        task.instructions ?? '',
        [],
        undefined,
        {
          projectName: project.name,
          projectDescription: project.description,
          knowledgeBase: knowledgeContext,
          parentTaskTitle: taskWithContext?.parentTask?.title ?? null,
          acceptanceCriteria: taskWithContext?.acceptanceCriteria ?? null,
          codeSummary: codeSummary ?? null,
        },
      );
    } catch {
      prBody = `## Generated by TaskToad AI\n\n**Task:** ${task.title}\n${task.description || ''}\n\n---\n*This PR was automatically generated by [TaskToad](https://tasktoad.dev).*`;
    }

    const result = await createPullRequest(ctx.repo, {
      repositoryId: ctx.repo.repositoryId,
      baseRefName: ctx.repo.defaultBranch,
      headRefName: ctx.plan.branchName,
      title: `feat: ${task.title}`,
      body: prBody,
    });

    // Create PR link record in database
    await ctx.prisma.gitHubPullRequestLink.create({
      data: {
        taskId: task.taskId,
        prNodeId: result.pullRequestId,
        prNumber: result.number,
        prUrl: result.url,
        prTitle: result.title,
        state: 'OPEN',
      },
    });

    return {
      success: true,
      data: { url: result.url, number: result.number, branch: ctx.plan.branchName },
    };
  },
};
