/**
 * Unified automation service: orchestrates the full flow from task to pull request.
 *
 * createPullRequestFromTask:
 *   1. Ensure repository exists (create if needed)
 *   2. Create branch from default branch
 *   3. Commit files to branch
 *   4. Open pull request
 */

import { PrismaClient } from '@prisma/client';
import { getProjectRepo, createRepoForProject } from './githubRepositoryService.js';
import { createBranch, commitFiles } from './githubCommitService.js';
import { createPullRequest } from './githubPullRequestService.js';
import type { CreatePullRequestFromTaskInput, PullRequestResult, GitHubRepoLink } from './githubTypes.js';
import { logApiError } from './githubLogger.js';
import { generateCommitMessage, enrichPRDescription } from '../ai/index.js';

const prisma = new PrismaClient();

function buildDefaultPRBody(
  task: { title: string; description: string | null },
  files: Array<{ path: string }>
): string {
  return [
    '## Generated by TaskToad AI',
    '',
    `**Task:** ${task.title}`,
    task.description ? `**Description:** ${task.description}` : '',
    '',
    '### Changes',
    ...files.map((f) => `- \`${f.path}\``),
    '',
    '---',
    '*This pull request was automatically generated by [TaskToad](https://tasktoad.dev).*',
  ]
    .filter(Boolean)
    .join('\n');
}

/**
 * Full automation: task -> branch -> commit -> pull request.
 *
 * All PRs appear as created by tasktoad[bot] because they use
 * the GitHub App installation token for authentication.
 */
export async function createPullRequestFromTask(
  input: CreatePullRequestFromTaskInput
): Promise<PullRequestResult> {
  const { projectId, taskId, files, apiKey } = input;

  // Load task details for PR metadata
  const task = await prisma.task.findUniqueOrThrow({
    where: { taskId },
    select: { title: true, description: true, instructions: true, projectId: true },
  });

  if (task.projectId !== projectId) {
    throw new Error('Task does not belong to the specified project');
  }

  // 1. Ensure repository exists
  let repo: GitHubRepoLink | null = await getProjectRepo(projectId);
  if (!repo) {
    // Look up the installation for this project's org
    const project = await prisma.project.findUniqueOrThrow({
      where: { projectId },
      select: { orgId: true },
    });

    // Find an installation for this org — requires at least one to be linked
    const installation = await prisma.gitHubInstallation.findFirst({
      where: { orgId: project.orgId },
    });

    if (!installation) {
      throw new Error(
        'No GitHub App installation found for this organization. Install the TaskToad GitHub App first.'
      );
    }

    repo = await createRepoForProject(projectId, installation.installationId, installation.accountLogin);
  }

  try {
    // 2. Create branch
    const { branchName, baseOid } = await createBranch(repo, taskId);

    // 3. Commit files — use AI-generated message if API key available
    let commitMessage = `AI: implement task ${task.title}`;
    if (apiKey) {
      try {
        commitMessage = await generateCommitMessage(apiKey, task.title, task.description ?? '', files);
      } catch {
        // Fall back to default commit message
      }
    }
    await commitFiles(
      repo,
      {
        branch: branchName,
        message: commitMessage,
        additions: files,
      },
      baseOid
    );

    // 4. Open pull request — use AI-enriched body if API key available
    let prBody: string;
    if (apiKey) {
      try {
        prBody = await enrichPRDescription(
          apiKey,
          task.title,
          task.description ?? '',
          task.instructions ?? '',
          files.map((f) => ({ path: f.path, language: '' }))
        );
      } catch {
        prBody = buildDefaultPRBody(task, files);
      }
    } else {
      prBody = buildDefaultPRBody(task, files);
    }

    const result = await createPullRequest(repo, {
      repositoryId: repo.repositoryId,
      baseRefName: repo.defaultBranch,
      headRefName: branchName,
      title: `feat: implement ${task.title}`,
      body: prBody,
    });

    // Create PR link record
    await prisma.gitHubPullRequestLink.create({
      data: {
        taskId,
        prNodeId: result.pullRequestId,
        prNumber: result.number,
        prUrl: result.url,
        prTitle: result.title,
        state: 'OPEN',
      },
    });

    return result;
  } catch (error) {
    logApiError('createPullRequestFromTask', error, { projectId, taskId });
    throw error;
  }
}
